"""Python view of the shared TS/Python contract (ai/spec/spec.v1.json).

Nothing about sizes, offsets or action semantics is hard-coded in Python:
everything comes from the JSON generated by ``ai/spec/gen-spec.ts``.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_SPEC_PATH = REPO_ROOT / "ai" / "spec" / "spec.v1.json"

_NP_DTYPES = {
    "u8": "<u1",
    "i16": "<i2",
    "u16": "<u2",
    "i32": "<i4",
    "u32": "<u4",
    "f32": "<f4",
}


def canonical_json(obj) -> str:
    """Same canonical form as spec.ts canonicalJson()."""
    return json.dumps(obj, sort_keys=True, separators=(",", ":"), ensure_ascii=False)


@dataclass(frozen=True)
class Preset:
    name: str
    GH: int
    GW: int
    K: int
    C: int
    NS: int
    FS: int
    record_size: int

    @property
    def cells(self) -> int:
        return self.GH * self.GW

    @property
    def slots(self) -> int:
        """Pointer-head size: TN slot + K player slots."""
        return self.K + 1

    @property
    def cell_head(self) -> int:
        """Cell-head size: AUTO + GH*GW cells."""
        return 1 + self.GH * self.GW


@dataclass(frozen=True)
class TypeInfo:
    id: int
    name: str
    ptr: bool
    tn: bool
    cell_group: int  # -1 none, -2 boat rows, 0..15 mask_cell row
    amount: str  # none | troops | count | gold


@dataclass(frozen=True)
class TensorSpec:
    name: str
    dtype: str
    shape: tuple[int, ...]
    offset: int
    bytes: int
    bits: int | None


class Spec:
    """Loaded spec.v1.json with helpers for records and masks."""

    CELL_NONE = -1
    CELL_BOAT = -2

    def __init__(self, raw: dict, path: str | None = None):
        body = {k: v for k, v in raw.items() if k != "spec_hash"}
        computed = hashlib.sha256(canonical_json(body).encode("utf-8")).hexdigest()
        stored = raw.get("spec_hash")
        if stored is not None and stored != computed:
            raise ValueError(
                f"spec hash mismatch in {path}: stored {stored}, computed {computed}"
            )
        self.raw = body
        self.path = path
        self.hash: str = computed
        self.version: int = body["version"]
        self.num_types: int = body["num_types"]
        self.num_amount: int = body["num_amount"]
        self.num_cell_groups: int = body["num_cell_groups"]
        self.intents_per_step: int = body["intents_per_step"]
        self.types: list[TypeInfo] = [
            TypeInfo(
                id=t["id"],
                name=t["name"],
                ptr=t["ptr"],
                tn=t["tn"],
                cell_group=t["cell_group"],
                amount=t["amount"],
            )
            for t in body["action_types"]
        ]
        self.type_ids = {t.name: t.id for t in self.types}
        self.cell_groups: list[int] = list(body["cell_groups"])
        self.cell_group_of_type = np.array([t.cell_group for t in self.types], dtype=np.int64)
        self.type_uses_ptr = np.array([t.ptr for t in self.types], dtype=bool)
        self.type_ptr_allows_tn = np.array([t.tn for t in self.types], dtype=bool)
        self.type_uses_cell = self.cell_group_of_type != self.CELL_NONE
        self.type_uses_amount = np.array([t.amount != "none" for t in self.types], dtype=bool)
        self.amount_bins = body["amount_bins"]
        self.troop_bin_names = [b["name"] for b in self.amount_bins["troops"]]
        # Troop bins that need a target player (MATCH): invalid when ptr == TN.
        self.match_bins = np.array(
            [b["kind"] == "match" for b in self.amount_bins["troops"]], dtype=bool
        )
        self.plane_channels: list[str] = body["plane_channels"]
        self.scalar_features: list[str] = body["scalar_features"]
        self.slot_features: list[str] = body["slot_features"]
        self.flags: dict[str, int] = body["flags"]
        self.header = body["header"]
        self.header_size: int = body["header_size"]
        self.protocol = body["protocol"]
        self.messages: dict[str, int] = body["protocol"]["messages"]
        self._presets: dict[str, Preset] = {}
        self._tensors: dict[str, dict[str, TensorSpec]] = {}
        for name, p in body["presets"].items():
            layout = body["layouts"][name]
            self._presets[name] = Preset(
                name=name,
                GH=p["GH"],
                GW=p["GW"],
                K=p["K"],
                C=p["C"],
                NS=p["NS"],
                FS=p["FS"],
                record_size=layout["record_size"],
            )
            self._tensors[name] = {
                t["name"]: TensorSpec(
                    name=t["name"],
                    dtype=t["dtype"],
                    shape=tuple(t["shape"]),
                    offset=t["offset"],
                    bytes=t["bytes"],
                    bits=t["bits"],
                )
                for t in layout["tensors"]
            }
        self._dtypes: dict[str, np.dtype] = {}

    # ------------------------------------------------------------------ load

    @staticmethod
    def load(path: str | Path | None = None) -> "Spec":
        p = Path(path) if path is not None else DEFAULT_SPEC_PATH
        with open(p, encoding="utf-8") as f:
            return Spec(json.load(f), str(p))

    # ---------------------------------------------------------------- layout

    def preset(self, name: str) -> Preset:
        return self._presets[name]

    def tensors(self, preset: str) -> dict[str, TensorSpec]:
        return self._tensors[preset]

    def record_dtype(self, preset: str) -> np.dtype:
        """Structured dtype over one record: header fields + tensors, explicit offsets."""
        dt = self._dtypes.get(preset)
        if dt is not None:
            return dt
        names, formats, offsets = [], [], []
        for f in self.header:
            names.append(f["name"])
            formats.append(_NP_DTYPES[f["dtype"]])
            offsets.append(f["offset"])
        for t in self._tensors[preset].values():
            names.append(t.name)
            formats.append((_NP_DTYPES[t.dtype], t.shape))
            offsets.append(t.offset)
        dt = np.dtype(
            {
                "names": names,
                "formats": formats,
                "offsets": offsets,
                "itemsize": self._presets[preset].record_size,
            }
        )
        self._dtypes[preset] = dt
        return dt

    def view_records(self, buf, preset: str, count: int | None = None, offset: int = 0) -> np.ndarray:
        """Zero-copy structured view over consecutive records in ``buf``."""
        dt = self.record_dtype(preset)
        if count is None:
            count = (len(buf) - offset) // dt.itemsize
        return np.frombuffer(buf, dtype=dt, count=count, offset=offset)

    # ----------------------------------------------------------------- masks

    def _unpack(self, packed: np.ndarray, bits: int) -> np.ndarray:
        return np.unpackbits(packed, axis=-1, count=bits, bitorder="little").astype(bool)

    def unpack_masks(self, rec: np.ndarray, preset: str) -> dict[str, np.ndarray]:
        """Bit-packed masks of structured records → bool arrays.

        Returns {"type": [n,31], "ptr": [n,31,K+1], "amount": [n,31,12],
        "cell": [n,16,1+cells], "boat_cell": [n,K+1,1+cells]}.
        """
        ts = self._tensors[preset]
        rec = np.atleast_1d(rec)
        return {
            "type": self._unpack(np.ascontiguousarray(rec["mask_type"]), ts["mask_type"].bits),
            "ptr": self._unpack(np.ascontiguousarray(rec["mask_ptr"]), ts["mask_ptr"].bits),
            "amount": self._unpack(np.ascontiguousarray(rec["mask_amount"]), ts["mask_amount"].bits),
            "cell": self._unpack(np.ascontiguousarray(rec["mask_cell"]), ts["mask_cell"].bits),
            "boat_cell": self._unpack(
                np.ascontiguousarray(rec["mask_boat_cell"]), ts["mask_boat_cell"].bits
            ),
        }

    @staticmethod
    def pack_bits(mask: np.ndarray) -> np.ndarray:
        """Inverse of unpack along the last axis (LSB-first)."""
        return np.packbits(mask.astype(bool), axis=-1, bitorder="little")

    # ----------------------------------------------------------------- flags

    def flag(self, name: str) -> int:
        return self.flags[name]

    def has_flag(self, flags: np.ndarray, name: str) -> np.ndarray:
        return (flags & self.flags[name]) != 0
